version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      SA_PASSWORD: $SA_PASSWORD
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
